name: flutter_html
description: A Flutter widget for rendering static html tags as Flutter widgets with image caching support. (Will render over 70 different html tags!)
version: 0.9.6
author: Dominic Orga <dominicorga@gmail.com>
homepage: https://github.com/DominicOrga/flutter_html

environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: '>=0.5.0'

dependencies:
  html: ^0.13.3
  flutter:
    sdk: flutter
  url_launcher: ^5.0.2
  cached_network_image: ^0.7.0
  flutter_cache_manager: ^0.3.2
  chewie: ^0.9.7
  video_player: ^0.10.0+5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
